  name: Debug Token Replacement
  on:
    push:
      branches:
        - main

  jobs:
    replace-token:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Set Up Token
          env:
            TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
          run: |
            if [[ -z "${TOKEN}" ]]; then
              echo "TOKEN is undefined or empty"
              exit 1
            else
              echo "TOKEN is defined and has length: ${#TOKEN}"
            fi

        - name: Replace Token in main.js
          run: |
            sed -i "s/__GITHUB_TOKEN_PLACEHOLDER__/${TOKEN}/g" main.js
            echo "Replaced token in main.js"
            grep 'const GITHUB_TOKEN' main.js

        - name: Debug Placeholder
          run: |
            echo "Content of main.js before replacement:"
            cat main.js

        - name: Test sed Matching
          run: |
            echo "Debugging sed command..."
            grep "__GITHUB_TOKEN_PLACEHOLDER__" main.js && echo "Placeholder found" || echo "Placeholder not found"

        - name: Replace Token in main.js
          run: |
            sed -i "s|__GITHUB_TOKEN_PLACEHOLDER__|${TOKEN}|g" main.js
            echo "Content of main.js after replacement:"
            cat main.js
