name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Before Token Replacement
        run: |
          echo "Before token replacement:"
          cat main.js  # Display the content of main.js before replacement

      - name: Replace Placeholder with Token
        env:
          TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
        run: |
          echo "Replacing token..."
          sed -i "s/__GITHUB_TOKEN_PLACEHOLDER__/${TOKEN}/g" main.js
          
      - name: Debug After Token Replacement
        run: |
          echo "After token replacement:"
          cat main.js  # Display the content of main.js after replacement

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.M_GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Debug Token Replacement
        run: |
          echo "Replaced token:" $(grep 'const GITHUB_TOKEN' main.js)

      - name: Replace Placeholder with Token
        env:
          TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
        run: |
          echo "Replacing token..."
          sed -i "s/__GITHUB_TOKEN_PLACEHOLDER__/$TOKEN/g" main.js || exit 1
          cat main.js  # Verify replacement

      - name: Debug Token Replacement
        run: |
          if [[ -z "${TOKEN}" ]]; then
            echo "TOKEN is undefined or empty"
          else
            echo "Token length: ${#TOKEN}"
          fi
          echo "Replaced token:" $(grep 'const GITHUB_TOKEN' main.js)



